### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by bugok**
s/commends/command/g

### CODE REVIEW

**Comment by bugok** [comment]
I don't think the CI failure is related to my change.

**Comment by jaymzh** [comment]
Thanks! re-running lint

**Comment by jaymzh** [comment]
Looks like the rubocop check fails if there's no ruby in the PR. How odd. I'm approving this, I"ll merge in a bit, but I wanna see if I can fix this first.

**Comment by jaymzh** [comment]
Oh. Looks like GITHUB_SECRET somehow fails on PRs from external contributors...

**Pull request merged**
